# Generated by Django 3.0.2 on 2020-02-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stallname', models.CharField(max_length=30, verbose_name='档口名称')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
                ('consignee', models.CharField(max_length=20, verbose_name='收货人')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
            ],
            options={
                'verbose_name': '档口信息',
                'verbose_name_plural': '档口信息',
            },
        ),
        migrations.AddConstraint(
            model_name='stall',
            constraint=models.UniqueConstraint(fields=('stallname', 'address'), name='unique_stall'),
        ),
    ]
