# Generated by Django 3.0.2 on 2020-02-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(max_length=20, verbose_name='仓库名称')),
                ('warehouse_area', models.CharField(blank=True, max_length=20, null=True, verbose_name='仓库区域')),
            ],
            options={
                'verbose_name': '仓库信息',
                'verbose_name_plural': '仓库信息',
            },
        ),
        migrations.AddConstraint(
            model_name='storage',
            constraint=models.UniqueConstraint(fields=('warehouse', 'warehouse_area'), name='unique_area'),
        ),
    ]
