# Generated by Django 3.0.2 on 2020-02-01 16:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargos', '0001_initial'),
        ('stalls', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='流水号')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('truck_number', models.CharField(blank=True, default='未分配车辆', max_length=20, null=True, verbose_name='车号')),
                ('trucker', models.CharField(blank=True, max_length=20, null=True, verbose_name='车主')),
                ('trucker_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('stall_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='档口联系电话')),
                ('destination', models.CharField(blank=True, max_length=50, null=True, verbose_name='目的地')),
                ('total_quantity', models.IntegerField(blank=True, null=True, verbose_name='总数量')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='总金额')),
                ('truckage', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='搬运费')),
                ('deadweight', models.FloatField(blank=True, null=True, verbose_name='载重量')),
                ('weight_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='超载每吨补充费用')),
                ('overweight', models.FloatField(blank=True, null=True, verbose_name='超载重量')),
                ('overweight_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='超载费用')),
                ('cartage', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='车费')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='合计费用')),
                ('prepay', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='预付费用')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '货单流水号',
                'verbose_name_plural': '货单流水号',
            },
        ),
        migrations.CreateModel(
            name='ManifestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='货物数量')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='单价')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=13, null=True, verbose_name='金额')),
                ('is_output', models.BooleanField(default=False, verbose_name='是否出库')),
                ('is_paycollect', models.BooleanField(default=False, verbose_name='是否回款')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cargos.CargoBoxType', verbose_name='包装类型')),
                ('cargo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cargos.Cargo', verbose_name='关联库存')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.CustomerLabel', verbose_name='商标名称')),
                ('stallname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stalls.Stall', verbose_name='档口名称')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cargos.CargoType', verbose_name='货品类型')),
                ('uuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manifests.Manifest', verbose_name='流水号')),
            ],
            options={
                'verbose_name': '货单详细信息',
                'verbose_name_plural': '货单详细信息',
            },
        ),
        migrations.AddConstraint(
            model_name='manifestinfo',
            constraint=models.UniqueConstraint(fields=('uuid', 'stallname', 'cargo', 'label', 'type'), name='unique_manifest'),
        ),
    ]
