# Generated by Django 3.0.2 on 2020-02-01 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0001_initial'),
        ('manifests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestinfo',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cargos.Cargo', verbose_name='关联库存'),
        ),
    ]
