# Generated by Django 3.0.2 on 2020-02-01 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0001_initial'),
        ('customers', '0001_initial'),
        ('manifests', '0003_auto_20200201_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestinfo',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cargos.CargoBoxType', verbose_name='包装类型'),
        ),
        migrations.AlterField(
            model_name='manifestinfo',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.CustomerLabel', verbose_name='商标名称'),
        ),
        migrations.AlterField(
            model_name='manifestinfo',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cargos.CargoType', verbose_name='货品类型'),
        ),
    ]
