# Generated by Django 3.0.2 on 2020-02-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0004_auto_20200201_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestinfo',
            name='detail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
    ]
